# To use Gemfiles see bundler.io
# To install: sudo gem install bundler
# To use: bundler install or bundler update
# To remove all gems not required in this file:
#   sudo bundle clean --force # Note: normally sudo isn't good for bundle but this is an exception
# This helps ensure that you aren't depending on a gem that isn't installed from this list
# To bundle gems for production or staging, recommend:
#   bundle install --without test
# If you want to manage different ruby installations with different gemsets for different projects
# Consider installing RVM to help manage that.
source 'https://rubygems.org'
gem 'logger'
gem 'rake'
gem 'pg', '>= 0.17.1'
gem 'actionpack', '>=4.1.6'
gem 'activesupport', '>=4.1.6'
gem 'activerecord', '>=4.1.6'
gem 'actionview', '>=4.1.6'
gem 'htmlentities', '>= 4.3.2'
gem 'nokogiri', '>= 1.6.3.1'
gem 'redis', '>= 3.1.0'
gem 'sinatra', '>= 1.4.5'
gem 'sinatra-contrib', '>= 1.4.2'
gem 'thin', '>= 1.6.2' # development, maybe production
gem 'rerun' # process reload agent, helpful for sinatra development
gem 'bcrypt', '>=3.1.7'
gem 'chronic'
gem 'chronic_duration'
# squasher - used in development to compress migration files
group :test do
  gem 'minitest', '>= 5.4.0'
  gem 'database_cleaner', '>= 1.3.0'
  gem 'debugger'
end

