    password_salt: 8JVjt2w43z
    deploy_password: uRd0lhlf3Qwh8c51f1zB
    lt_admin_password: CTyKgyW9z4jNeztbvt3G
    root_password: uTcuEz1q41rCSuRzC2Mp
    do_client_id: 74b0b05bbd6c960647210e77c87b7886
    do_api_key: cc51d35a57ceaa15ccb13fe47e1f9cd7
    git_deploy_token: 792de6a69ea9f5e82e17ca9d46d920b19462cfe4
