development:
  adapter: postgresql
  database: lr_search_dev
  host: localhost
  username: username
  password: password
  encoding: utf8
test:
  adapter: postgresql
  database: lr_search_test
  host: localhost
  username: username
  password: password
  encoding: utf8
