# to add a new db environment, create it here and then run
# rake db:create RAILS_ENV=[name of new env]
development:
  adapter: postgresql
  encoding: UTF8
  database: lt_dev_db
  pool: 5
  host: 10.21.11.133
  port: 5432
  username: learntaculous
  password: lt_dev_xyz_123
  tablespace: learntaculous_ts
test:
  adapter: postgresql
  encoding: UTF8
  database: lt_test_db
  pool: 5
  host: 10.21.11.133
  port: 5432
  username: learntaculous
  password: lt_dev_xyz_123
  tablespace: learntaculous_ts
