adapter: postgresql
encoding: UTF8
database: <%= ENV['POSTGRESQL_DATABASE'] %>
pool: 5
host: <%= ENV['POSTGRESQL_ADDRESS'] %>
port: 5432
template: template0
username: <%= ENV['POSTGRESQL_USERNAME'] %>
password: <%= ENV['POSTGRESQL_PASSWORD'] %>
