# Requires python dopy: sudo pip install dopy
# To run this file:
# sudo ansible-playbook -i staging-hosts.rb --ask-vault-pass create-do-servers.yml
#   Requires "sudo" b/c it needs to write to the local /etc/hosts file
---
- hosts: common
  serial: 1
  vars: 
    ansible_connection: "local"
  gather_facts: False
  tasks:
  # secrets.yml contains do_client_id/do_api_key
  - include_vars: ./secrets/secrets.yml
  - name: Create Digital Ocean server (this will take a while...)
    digital_ocean: >
        state=present
        command=droplet
        unique_name=yes
        wait_timeout=500
        backups_enabled=no
        private_networking=yes
        client_id="{{do_client_id}}"
        api_key="{{do_api_key}}"
        name="{{inventory_hostname}}"
        ssh_key_ids=422316
        size_id=63
        region_id=4
        image_id=6918990
    register: new_server
  - debug: "msg='Created server: {{new_server.droplet.name}} / IP: {{new_server.droplet.ip_address}}'"
  - name: Create DNS
    digital_ocean_domain: >
      state=present
      name="{{ inventory_hostname }}.learningtapestry.com"
      ip="{{ new_server.droplet.ip_address }}"
      client_id="{{do_client_id}}"
      api_key="{{do_api_key}}"
  - name: Add/replace hosts file entry on local computer (for staging servers)
    lineinfile: >
      dest=/etc/hosts
      state=present
      regexp="{{ inventory_hostname }}.learningtapestry.com"
      line="{{new_server.droplet.ip_address}} {{ inventory_hostname }}.learningtapestry.com"
    when: "'staging' in inventory_hostname"

# Get SSH key info
# https://api.digitalocean.com/v1/ssh_keys/?client_id=[id]&api_key=[key]
# {"status":"OK","ssh_keys":[{"id":422316,"name":"Learning Tapestry Public Key"}]}

# DO API v1 size ID's
# https://api.digitalocean.com/v1/sizes/?client_id=[id]&api_key=[key]
# {"status":"OK","sizes":[
# {"id":66,"name":"512MB","slug":"512mb","memory":512,"cpu":1,"disk":20,"cost_per_hour":0.00744,"cost_per_month":"5.0"},
# {"id":63,"name":"1GB","slug":"1gb","memory":1024,"cpu":1,"disk":30,"cost_per_hour":0.01488,"cost_per_month":"10.0"},
# {"id":62,"name":"2GB","slug":"2gb","memory":2048,"cpu":2,"disk":40,"cost_per_hour":0.02976,"cost_per_month":"20.0"},
# {"id":64,"name":"4GB","slug":"4gb","memory":4096,"cpu":2,"disk":60,"cost_per_hour":0.05952,"cost_per_month":"40.0"},
# {"id":65,"name":"8GB","slug":"8gb","memory":8192,"cpu":4,"disk":80,"cost_per_hour":0.11905,"cost_per_month":"80.0"},
# {"id":61,"name":"16GB","slug":"16gb","memory":16384,"cpu":8,"disk":160,"cost_per_hour":0.2381,"cost_per_month":"160.0"},
# {"id":60,"name":"32GB","slug":"32gb","memory":32768,"cpu":12,"disk":320,"cost_per_hour":0.47619,"cost_per_month":"320.0"},
# {"id":70,"name":"48GB","slug":"48gb","memory":49152,"cpu":16,"disk":480,"cost_per_hour":0.71429,"cost_per_month":"480.0"},
# {"id":69,"name":"64GB","slug":"64gb","memory":65536,"cpu":20,"disk":640,"cost_per_hour":0.95238,"cost_per_month":"640.0"}]}

# DO API v1 edited request/response for images: ubuntu 14.04:
# https://api.digitalocean.com/images/?client_id=[id]&api_key=[key]&filter=global
# {"id":6918990,
#  "name":"14.04 x64",
#  "slug":"ubuntu-14-04-x64","distribution":"Ubuntu","public":true,
#  "regions":[1,2,3,4,5,6,7,8,9],
#  "region_slugs":["nyc1","ams1","sfo1","nyc2","ams2","sgp1","lon1","nyc3","ams3"]}

# references
# https://github.com/garethr/ansible-provisioner
# https://sendgrid.com/blog/ansible-and-digital-ocean/

