---
  #   ssh-agent bash
  #   ssh-add ./secrets/id_deploy
  #   ansible-playbook -i [lt_env]-hosts.rb debug-playbook.yml 
- hosts: web
  vars:
    ansible_ssh_host: "{{inventory_hostname}}.learningtapestry.com"
    ansible_ssh_user: deploy
    ansible_ssh_private_key_file: ./secrets/id_deploy
  tasks:
  - stat: ruby
    register: rv
  - debug: "msg='{{rv.stdout}}'"
  - debug: "msg=hello"
  - debug: "msg='test test:{{lt_code_folder}} value'"
  # - include_vars: ./secrets/secrets.yml
  # - include_vars: "./secrets/{{lt_env}}_secrets.yml"
  # - debug: "msg='{{hostvars[item]['ansible_eth1']['ipv4']['address']}}'"
  #   with_items: groups.db
# - hosts: db
#   gather_facts: False
#   vars:
#     ansible_ssh_host: "{{inventory_hostname}}.learningtapestry.com"
#     ansible_ssh_user: deploy
#     ansible_ssh_private_key_file: ./secrets/id_deploy
#   tasks:
#   - debug: "msg='{{hostvars[item]['ansible_eth1']['ipv4']['address']}}'"
#     with_items: groups.common
  # - name: Update PG access template
  #   template: >
  #     src=./roles/db/files/pg_hba.conf.j2
  #     dest=/etc/postgresql/9.3/main/pg_hba.conf
  #     owner=postgres
  #   sudo: yes
  # - name: Add new hosts file entry for server
  #   lineinfile: >
  #     dest=/etc/hosts
  #     state=present
  #     regexp="{{ inventory_hostname }}.learningtapestry.com"
  #     line="10.0.0.1 {{ inventory_hostname }}.learningtapestry.com"
# ---
# - hosts: local
#   vars:
#     ansible_connection: local
#   gather_facts: False
#   tasks:
  # - name: Lookup server's current NS record
  #   shell: host {{ inventory_hostname }}.learningtapestry.com ns1.digitalocean.com | grep -o address\\s.* | grep -o [0-9.]*
  #   register: server_ip
  # - name: inventory_hostname variable
  #   debug: msg={{inventory_hostname}}/{{server_ip.stdout}}
  # - name: Add domain entry for ns
  #   shell: host ns1.digitalocean.com | grep -o address\\s.* | grep -o [0-9.]*
  #   register: ns_server_ip
  # - lineinfile: >
  #     dest=/etc/dhcp/dhclient.conf
  #     state=present
  #     line="prepend domain-name-servers {{ns_server_ip.stdout}}"
  #     insertafter="^#\s*prepend"
  #   sudo: yes
  # - shell: echo sudo service network-manager restart
  # - name: Check variable
  #   debug: var=ansible_connection
  # - name: Remove old SSH key file entries
  #   local_action: command rm ~./ssh/known_hosts.old removes=True
  #   local_action: command ssh-keygen -R {{ inventory_hostname }}.learningtapestry.com
  #   local_action: command rm ~./ssh/known_hosts.old removes=True
  #   local_action: command ssh-keygen -R {{ server_ip.stdout }}
  # - name: Confirm running to completion
  #   debug: "msg=Ran to completion"
    # - name: Check variable
    #   debug: var=groups["staging"]
    # - name: Dump all vars
    #   action: template src=dumpall.j2 dest=/tmp/ansible.all