---
  # run: 
  #   ssh-agent bash
  #   ssh-add ./secrets/id_deploy
  #   ansible-playbook -i staging-hosts.rb --ask-sudo-pass install-common-setup.yml 
  # sudo password is for user deploy
  - hosts: common
    remote_user: deploy
    sudo: yes
    vars:
      ansible_ssh_host: "{{inventory_hostname}}.learningtapestry.com"
      ansible_ssh_user: deploy
      ansible_ssh_private_key_file: ./secrets/id_deploy
    tasks:
    - name: General | Install required packages (this will take awhile..)
      #apt: pkg={{ item }} state=installed update_cache=true
      action: apt pkg={{ item }} state=installed update_cache=true
      with_items:
        - build-essential
        - unzip
        - zip
        - ufw
        - unattended-upgrades
        - postfix # used so boxes can send email
        - byobu
        - git

    - name: Copy the unattended-upgrades file
      copy: src=roles/common/files/50unattended-upgrades dest=/etc/apt/apt.conf.d/50unattended-upgrades
    - copy: src=roles/common/files/20auto-upgrades dest=/etc/apt/apt.conf.d/20auto-upgrades

    - name:  UFW - Allow port 22
      ufw: rule=allow port=22 proto=tcp

    - name:  UFW - Deny all others by default
      ufw: policy=deny direction=incoming

    - name:  UFW - Enable logging
      ufw: logging=on

    - name:  UFW - enable, deny traffic by default
      ufw: state=enabled

