---
  # run: 
  #   ssh-agent bash
  #   ssh-add ./secrets/id_deploy
  #   ansible-playbook -i staging-hosts.rb --ask-vault-pass --ask-sudo-pass install-web-setup.yml 
  # sudo password is for user deploy
  - hosts: web
    remote_user: deploy
    sudo: yes
    vars:
      ansible_ssh_host: "{{inventory_hostname}}.learningtapestry.com"
      ansible_ssh_user: deploy
      ansible_ssh_private_key_file: ./secrets/id_deploy
    tasks: 
    # vault holds ssl_cert_password
    - include_vars: "./secrets/{{lt_env}}_secrets.yml"
    - name: Install Nginx prerequisites
      shell: sudo apt-get update
    - shell: sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 561F9B9CAC40B2F7
    - shell: touch /etc/apt/sources.list.d/passenger.list
    - lineinfile: >
        state=present
        insertafter=EOF
        dest=/etc/apt/sources.list.d/passenger.list
        line="deb https://oss-binaries.phusionpassenger.com/apt/passenger trusty main"
    - shell: "sudo chown root:root /etc/apt/sources.list.d/passenger.list"
    - shell: sudo chmod 600 /etc/apt/sources.list.d/passenger.list
    - shell: sudo apt-get update
    - action: apt pkg={{ item }} state=installed update_cache=true
      with_items:
        - nginx-extras
        - passenger
    - shell: rm -f /etc/nginx/sites-enabled/*
    - copy: src='./roles/web/files/nginx.learningtap.{{lt_env}}.conf' dest='/etc/nginx/sites-enabled/'
    - copy: >
        src=./roles/web/files/nginx.conf
        dest=/etc/nginx/nginx.conf
  # To verify if passenger is working: passenger-memory-stats

  # Install ssl certs in production
  # certs should be located at /learntap/secrets/ssl/learntap-ssl-production-certs.tar.gz.gpg
  # cert should be encrypted with gpg using aes256, with a passphrase stored in 
  # production_secrets.yml under key ssl_cert_password. CLI to encrypt is:
  # tar -C [folder to ssl certs] -czf learntap-ssl-production-certs.tar.gz --owner=root --group=root --mode=0400 .
  # gpg --symmetric --cipher-algo aes256 learntap-ssl-production-certs.tar.gz
    - shell: mkdir -p /etc/nginx/ssl
      when: "lt_env == 'production'"
    - shell: chown root:root /etc/nginx/ssl
      when: "lt_env == 'production'"
    - shell: chmod ugoa-rwx /etc/nginx/ssl
      when: "lt_env == 'production'"
    - shell: chmod u+r /etc/nginx/ssl
      when: "lt_env == 'production'"
    - copy: >
        src="~/learntap/secrets/ssl/learntap-ssl-production-certs.tar.gz.gpg"
        dest="/etc/nginx/ssl"
      when: "lt_env == 'production'"
    - shell: echo {{ssl_cert_password}} | gpg --passphrase-fd 0 -d learntap-ssl-production-certs.tar.gz.gpg > learntap-ssl-production-certs.tar.gz
      when: "lt_env == 'production'"
      args:
        chdir: /etc/nginx/ssl
      when: "lt_env == 'production'"
    - shell: tar xzf /etc/nginx/ssl/learntap-ssl-production-certs.tar.gz
      args:
        chdir: /etc/nginx/ssl
      when: "lt_env == 'production'"

