---
# This playbook deploys the whole application stack in this site.  

- name: apply common configuration to all nodes
  hosts: all
  remote_user: root
  vars_files:
    - 'vars/main.yml'

  roles:
    - common

- name: configure and deploy the webservers and application code
  hosts: webservers
  remote_user: root

  roles:
    - web

- name: deploy Postgres and configure the databases
  hosts: dbservers
  remote_user: root

  roles:
    - db
