---
  # run: 
  #   ssh-agent bash
  #   ssh-add ./secrets/id_deploy
  #   ansible-playbook -i staging-hosts.rb --ask-vault-pass --ask-sudo-pass update-web-application.yml 
  # sudo password is for user deploy
  - hosts: common
    vars:
      ansible_ssh_host: "{{inventory_hostname}}.learningtapestry.com"
      ansible_ssh_user: deploy
      ansible_ssh_private_key_file: ./secrets/id_deploy
    tasks:
      # This is just a stub task to give this inventory run something to do
    - debug: "msg='Collecting facts for server: {{inventory_hostname}}'"
  - hosts: web
    gather_facts: False
    remote_user: deploy
    sudo: yes
    vars:
      ansible_ssh_host: "{{inventory_hostname}}.learningtapestry.com"
      ansible_ssh_user: deploy
      ansible_ssh_private_key_file: ./secrets/id_deploy
    tasks: 
    - include: fragment-update-web-application.yml code_install_folder=/opt/learningtapestry