development:
  adapter: postgresql
  encoding: UTF8
  database: lt_dev_db
  pool: 5
  host: 127.0.0.1
  port: 5432
  username: lt_dbo
  password: lt_dev_xyz_123
  tablespace: learntaculous_ts

test:
  adapter: postgresql
  encoding: UTF8
  database: lt_test_db
  pool: 5
  host: 127.0.0.1
  port: 5432
  username: lt_dbo
  password: lt_dev_xyz_123
  tablespace: learntaculous_ts

staging:
  adapter: postgresql
  encoding: UTF8
  database: lt_staging_db
  pool: 5
  host: 127.0.0.1
  port: 5432
  username: lt_dbo
  password: lt_dev_xyz_123
  tablespace: learntaculous_ts

production:
  adapter: postgresql
  encoding: UTF8
  database: lt_prod_db
  pool: 5
  host: 127.0.0.1
  port: 5432
  username: lt_dbo
  password: lt_dev_xyz_123
  tablespace: learntaculous_ts
