# To use Gemfiles see bundler.io
# To install: sudo gem install bundler
# To use: bundler install or bundler update
# To remove all gems not required in this file:
#   sudo bundle clean --force # Note: normally sudo isn't good for bundle but this is an exception
# This helps ensure that you aren't depending on a gem that isn't installed from this list
# To bundle gems for production or staging, recommend:
#   bundle install --without test
source 'https://rubygems.org'
gem 'logger'
gem 'rake'
gem 'pg', '>= 0.17.1'
gem 'standalone_migrations', '>= 2.1.4'
gem 'htmlentities', '>= 4.3.2'
gem 'nokogiri', '>= 1.6.3.1'
group :test do
  gem 'minitest', '>= 5.4.0'
  gem 'database_cleaner', '>= 1.3.0'
  gem 'debugger'
end

